[package]
name = "windowlist"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
x11 = "2.21.0"
libc = "0.2.153"
toml = "0.8.12"
serde = {version = "1.0.201", features = ["derive"] }

[build-dependencies]
cc = "1.0.95"
